class TextStyle{
    inherit?:String = true,
    color?:String,
    backgroundColor?:String,
    fontSize?:String,
    fontWeight?:String,
    fontStyle?:String,
    letterSpacing?:String,
    wordSpacing?:String,
    textBaseline?:String,
    height?:String,
    leadingDistribution?:String,
    locale?:String,
    foreground?:String,
    background?:String,
    shadows?:String,
    fontFeatures?:String,
    decoration?:String,
    decorationColor?:String,
    decorationStyle?:String,
    decorationThickness?:String,
    debugLabel?:String,
    String? fontFamily,
    List<String>? fontFamilyFallback,
    String? package,
    this.overflow,
}